#!/usr/bin/env bash
# Script to configure Nginx server with a custom header

# Update package lists and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create index and custom 404 page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Update Nginx configuration
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Tolulope05 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl start nginx
