#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# Displays "I am invincible!!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!" ' TERM

while :
do
echo "To infinity and beyond"
sleep 2
done
